# Generated by Django 6.1 on 2026-09-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('kanji', models.CharField(max_length=64)),
                ('seal_text', models.CharField(max_length=64)),
                ('era_tag', models.CharField(max_length=64)),
                ('badge_text', models.CharField(max_length=32)),
                ('image', models.CharField(max_length=255)),
                ('image_alt', models.CharField(max_length=128)),
                ('seal_icon', models.CharField(default='fa-compass', max_length=32)),
                ('badge_icon', models.CharField(default='fa-compass', max_length=32)),
                ('summary', models.TextField()),
                ('meta_badges', models.JSONField(default=list)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Village',
                'verbose_name_plural': 'Villages',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
