/**
 * Naruto Clan Codex Data Module
 * Canonical data for the 6 Noble Clans and 5 Supporting Clans of the Shinobi World.
 */

export const CLAN_AURAS = {
  uchiha: 'radial-gradient(circle at 50% 50%, rgba(226, 90, 42, 0.18) 0%, rgba(8, 8, 8, 0) 70%)',
  senju: 'radial-gradient(circle at 50% 50%, rgba(16, 185, 129, 0.18) 0%, rgba(8, 8, 8, 0) 70%)',
  hyuga: 'radial-gradient(circle at 50% 50%, rgba(245, 158, 11, 0.18) 0%, rgba(8, 8, 8, 0) 70%)',
  uzumaki: 'radial-gradient(circle at 50% 50%, rgba(234, 88, 12, 0.18) 0%, rgba(8, 8, 8, 0) 70%)',
  nara: 'radial-gradient(circle at 50% 50%, rgba(168, 85, 247, 0.18) 0%, rgba(8, 8, 8, 0) 70%)',
  sarutobi: 'radial-gradient(circle at 50% 50%, rgba(245, 158, 11, 0.18) 0%, rgba(8, 8, 8, 0) 70%)',
};

export const NOBLE_CLANS_DATA = [
  {
    key: 'uchiha',
    label: '01 UCHIHA',
    dotClass: 'dot-uchiha',
    crestClass: 'crest-uchiha',
    frameClass: 'frame-uchiha',
    cardClass: 'card-uchiha',
    crestBadgeClass: 'badge-crimson',
    crestBadgeIcon: 'fa-eye',
    crestBadgeText: 'DŌJUTSU • SHARINGAN',
    crestKanji: 'うちは一族 • 炎の血統',
    image: '/assets/image/clan_uchiha.jpg',
    imageAlt: 'The Uchiha Clan',
    sealIcon: 'fa-fire',
    sealText: 'UCHIHA CLAN',
    cardBadgeClass: 'badge-crimson',
    eraTag: '【木ノ葉隠れ】 KONOHAGAKURE NOBLE',
    cardBadgeIcon: 'fa-eye',
    clanNum: 'CLAN 01',
    title: 'THE UCHIHA CLAN',
    kanji: 'うちは一族 • 写輪眼の宿命',
    desc: 'Descendants of Indra Ōtsutsuki, the Uchiha wield the legendary Sharingan dōjutsu. Renowned for unparalleled fire release techniques, genjutsu mastery, and the potent Susanoo avatar awakened through profound emotional bonds.',
    metaBadges: [
      { icon: 'fa-dna', text: 'Sharingan / Mangekyō' },
      { icon: 'fa-users', text: 'Madara, Itachi, Sasuke' },
      { icon: 'fa-shield', text: 'Fire / Genjutsu Specialist' },
    ],
  },
  {
    key: 'senju',
    label: '02 SENJU',
    dotClass: 'dot-senju',
    crestClass: 'crest-senju',
    frameClass: 'frame-senju',
    cardClass: 'card-senju',
    crestBadgeClass: 'badge-forest',
    crestBadgeIcon: 'fa-tree',
    crestBadgeText: 'KEKKEI GENKAI • WOOD RELEASE',
    crestKanji: '千手一族 • 森の意志',
    image: '/assets/image/clan_senju.jpg',
    imageAlt: 'The Senju Clan',
    sealIcon: 'fa-tree',
    sealText: 'SENJU CLAN',
    cardBadgeClass: 'badge-forest',
    eraTag: '【木ノ葉隠れ】 FOUNDING LINEAGE',
    cardBadgeIcon: 'fa-tree',
    clanNum: 'CLAN 02',
    title: 'THE SENJU CLAN',
    kanji: '千手一族 • 千の手を持つ一族',
    desc: 'Descendants of Asura Ōtsutsuki and co-founders of Konohagakure. Celebrated as the "Clan with a Thousand Skills," they mastered all chakra natures and inherited the unbreakable Will of Fire, with Hashirama awakening legendary Wood Release.',
    metaBadges: [
      { icon: 'fa-dna', text: 'Wood Release (Mokuton)' },
      { icon: 'fa-users', text: 'Hashirama, Tobirama, Tsunade' },
      { icon: 'fa-shield', text: 'All-Nature Mastery' },
    ],
  },
  {
    key: 'hyuga',
    label: '03 HYŪGA',
    dotClass: 'dot-hyuga',
    crestClass: 'crest-hyuga',
    frameClass: 'frame-hyuga',
    cardClass: 'card-hyuga',
    crestBadgeClass: 'badge-gold',
    crestBadgeIcon: 'fa-eye-low-vision',
    crestBadgeText: 'DŌJUTSU • ALL-SEEING BYAKUGAN',
    crestKanji: '日向一族 • 白眼と柔拳',
    image: '/assets/image/clan_hyuga.jpg',
    imageAlt: 'The Hyūga Clan',
    sealIcon: 'fa-eye',
    sealText: 'HYŪGA CLAN',
    cardBadgeClass: 'badge-gold',
    eraTag: '【木ノ葉隠れ】 NOBLEST HOUSE',
    cardBadgeIcon: 'fa-eye-low-vision',
    clanNum: 'CLAN 03',
    title: 'THE HYŪGA CLAN',
    kanji: '日向一族 • 木ノ葉最古の名門',
    desc: 'Direct descendants of Hamura Ōtsutsuki possessing the pure Byakugan eye. Their near-360° chakra perception enables the lethal Gentle Fist (Jūken) martial art, closing tenketsu chakra pathways with surgical precision.',
    metaBadges: [
      { icon: 'fa-dna', text: 'Byakugan (白眼)' },
      { icon: 'fa-users', text: 'Neji, Hinata, Hiashi' },
      { icon: 'fa-shield', text: 'Gentle Fist / Eight Trigrams' },
    ],
  },
  {
    key: 'uzumaki',
    label: '04 UZUMAKI',
    dotClass: 'dot-uzumaki',
    crestClass: 'crest-uzumaki',
    frameClass: 'frame-uzumaki',
    cardClass: 'card-uzumaki',
    crestBadgeClass: 'badge-orange',
    crestBadgeIcon: 'fa-certificate',
    crestBadgeText: 'FŪINJUTSU • VITALITY SEAL',
    crestKanji: 'うずまき一族 • 渦潮と封印',
    image: '/assets/image/clan_uzumaki.jpg',
    imageAlt: 'The Uzumaki Clan',
    sealIcon: 'fa-certificate',
    sealText: 'UZUMAKI CLAN',
    cardBadgeClass: 'badge-orange',
    eraTag: '【渦潮隠れ】 SEALING MASTERS',
    cardBadgeIcon: 'fa-certificate',
    clanNum: 'CLAN 04',
    title: 'THE UZUMAKI CLAN',
    kanji: 'うずまき一族 • 渦潮の生命力',
    desc: 'Distant blood relatives of the Senju hailing from Uzushiogakure. Renowned for boundless life force, immense chakra reserves, and forbidden Fūinjutsu sealing chains capable of binding even Nine-Tails tailed beasts.',
    metaBadges: [
      { icon: 'fa-dna', text: 'Adamantine Sealing Chains' },
      { icon: 'fa-users', text: 'Naruto, Kushina, Mito, Nagato' },
      { icon: 'fa-shield', text: 'Fūinjutsu / High Vitality' },
    ],
  },
  {
    key: 'nara',
    label: '05 NARA',
    dotClass: 'dot-nara',
    crestClass: 'crest-nara',
    frameClass: 'frame-nara',
    cardClass: 'card-nara',
    crestBadgeClass: 'badge-purple',
    crestBadgeIcon: 'fa-moon',
    crestBadgeText: 'HIDEN • SHADOW MANIPULATION',
    crestKanji: '奈良一族 • 影真似と知略',
    image: '/assets/image/clan_nara.jpg',
    imageAlt: 'The Nara Clan',
    sealIcon: 'fa-moon',
    sealText: 'NARA CLAN',
    cardBadgeClass: 'badge-purple',
    eraTag: '【木ノ葉隠れ】 TACTICAL ARCHIVE',
    cardBadgeIcon: 'fa-moon',
    clanNum: 'CLAN 05',
    title: 'THE NARA CLAN',
    kanji: '奈良一族 • 鹿と知略の影',
    desc: 'Famed for their genius intellect, herbal medicinal wisdom, and sacred deer sanctuary. The Nara command Hiden Shadow Manipulation ninjutsu, serving as top military advisors and Hokage strategists across generations.',
    metaBadges: [
      { icon: 'fa-dna', text: 'Shadow Imitation (Kagemane)' },
      { icon: 'fa-users', text: 'Shikamaru, Shikaku, Shikadai' },
      { icon: 'fa-shield', text: 'Ino-Shika-Chō Strategist' },
    ],
  },
  {
    key: 'sarutobi',
    label: '06 SARUTOBI',
    dotClass: 'dot-sarutobi',
    crestClass: 'crest-sarutobi',
    frameClass: 'frame-sarutobi',
    cardClass: 'card-sarutobi',
    crestBadgeClass: 'badge-amber',
    crestBadgeIcon: 'fa-fire-flame-curved',
    crestBadgeText: 'ALL-NATURE • FIRE RELEASE',
    crestKanji: '猿飛一族 • 飛猿の覚悟',
    image: '/assets/image/clan_sarutobi.jpg',
    imageAlt: 'The Sarutobi Clan',
    sealIcon: 'fa-fire-flame-curved',
    sealText: 'SARUTOBI CLAN',
    cardBadgeClass: 'badge-amber',
    eraTag: '【木ノ葉隠れ】 WILL OF FIRE PILLAR',
    cardBadgeIcon: 'fa-fire-flame-curved',
    clanNum: 'CLAN 06',
    title: 'THE SARUTOBI CLAN',
    kanji: '猿飛一族 • 火遁と忍の覚悟',
    desc: 'One of the earliest clans to pledge allegiance to the newly founded Leaf Village. Famed for fierce Fire Release mastery, monkey summons, and the versatile multi-nature genius exemplified by the "Professor" Hiruzen Sarutobi.',
    metaBadges: [
      { icon: 'fa-dna', text: 'High-Level Fire Release' },
      { icon: 'fa-users', text: 'Hiruzen, Asuma, Konohamaru' },
      { icon: 'fa-shield', text: 'Five-Nature Versatility' },
    ],
  },
];

export const SUPPORTING_CLANS_DATA = [
  {
    id: 'aburame',
    name: 'ABURAME CLAN',
    kanji: '油女一族 • 寄壊蟲の巣',
    icon: 'fa-bug',
    desc: 'Symbiotic masters who house parasitic Kikaichū insects within their bodies, draining enemy chakra in silence.',
    badge1: 'Insect Hiden',
    badge2: 'Konohagakure',
  },
  {
    id: 'akimichi',
    name: 'AKIMICHI CLAN',
    kanji: '秋道一族 • 倍化の術',
    icon: 'fa-cubes-stacked',
    desc: 'Wielders of the Yang Release Multi-Size Technique, converting body calories into crushing physical force and chakra wings.',
    badge1: 'Calorie Expansion',
    badge2: 'Ino-Shika-Chō',
  },
  {
    id: 'inuzuka',
    name: 'INUZUKA CLAN',
    kanji: '犬塚一族 • 獣人合体',
    icon: 'fa-paw',
    desc: 'Canine tracking specialists bonded with canine Ninken partners from birth, executing lethal Man-Beast Taijutsu.',
    badge1: 'Ninken Synergy',
    badge2: 'Konohagakure',
  },
  {
    id: 'yamanaka',
    name: 'YAMANAKA CLAN',
    kanji: '山中一族 • 心転身の術',
    icon: 'fa-brain',
    desc: 'Sensory telepaths and espionage experts commanding Mind Body Switch techniques to hijack enemy consciousness.',
    badge1: 'Telepathic Espionage',
    badge2: 'Ino-Shika-Chō',
  },
  {
    id: 'kaguya',
    name: 'KAGUYA CLAN',
    kanji: 'かぐや一族 • 屍骨脈',
    icon: 'fa-bone',
    desc: 'Extinct battle-hungry Kirigakure lineage wielding the rare Shikotsumyaku ability to manipulate skeletal bone density at will.',
    badge1: 'Shikotsumyaku Bone',
    badge2: 'Kirigakure / Extinct',
  },
];
