/**
 * CANONICAL TAILED BEASTS (BIJUU) DATASET
 * Contains tactical stage definitions, elemental affinities, deterrence ratings,
 * jinchūriki bonds, and combat mythology for the Nine Bijuu.
 */

export const BIJUU_NAV_LINKS = [
  { id: 'bijuu-shukaku', num: '01', name: 'SHUKAKU' },
  { id: 'bijuu-matatabi', num: '02', name: 'MATATABI' },
  { id: 'bijuu-isobu', num: '03', name: 'ISOBU' },
  { id: 'bijuu-son-goku', num: '04', name: 'SON GOKŪ' },
  { id: 'bijuu-kokuo', num: '05', name: 'KOKUŌ' },
  { id: 'bijuu-saiken', num: '06', name: 'SAIKEN' },
  { id: 'bijuu-chomei', num: '07', name: 'CHŌMEI' },
  { id: 'bijuu-gyuki', num: '08', name: 'GYŪKI' },
  { id: 'bijuu-kurama', num: '09', name: 'KURAMA' },
  {
    id: 'jinchuriki-vessels-section',
    num: 'VESSELS',
    icon: 'fa-solid fa-person-burst',
    name: 'THE VESSELS',
    isVessel: true,
  },
];

export const BIJUU_DATA = [
  {
    id: 'bijuu-shukaku',
    num: '01',
    tailNum: '01 TAIL',
    tailKanji: '一尾 (ICHIBI)',
    stageClass: 'stage-shukaku',
    auraClass: 'aura-shukaku',
    badgeThemeClass: 'badge-sand-theme',
    domainIcon: 'fa-wind',
    domainTag: 'DESERT STORM // SUNAGAKURE TRADITION',
    frameClass: 'frame-shukaku',
    image: '/assets/image/bijuu_01_shukaku.png',
    imageAlt: 'Shukaku the One-Tail',
    imgClass: 'img-shukaku',
    stampClass: 'stamp-sand',
    stampKanji: '砂',
    stampLabel: 'DESERT SEAL',
    metrics: [
      {
        label: 'ELEMENTAL AFFINITIES',
        value: 'WIND (風) • EARTH (土) • MAGNET (磁)',
        valueClass: 'highlight-gold',
      },
      {
        label: 'COMBAT ARCHETYPE',
        value: 'CURSED JUINJUTSU & SAND MANIPULATION',
      },
      {
        label: 'DETERRENCE STATUS',
        value: 'SOVEREIGN DEFENDER OF SUNA',
        valueClass: 'highlight-green',
      },
    ],
    intelBadgeIcon: 'fa-shield-cat',
    intelBadgeText: 'BIJUU DOSSIER // 01',
    name: 'SHUKAKU',
    nameClass: '',
    kanjiTitle: '一尾・守鶴 (THE SAND INCARNATION)',
    kanjiClass: '',
    synopsis:
      'The One-Tail of Sunagakure, manifesting as a gigantic tanuki patterned with natural black cursed seal formula (Juinjutsu). Possessing pride as vast as the desert dunes, Shukaku controls sand with supernatural fluidity and unleashes deafening Wind Release air bullets capable of leveling rocky valleys.',
    connectionBorderClass: 'border-sand',
    historicalVillage: 'Sunagakure (Hidden Sand)',
    historicalVillageIcon: 'fa-wind',
    historicalVillageClass: 'text-gold',
    primaryJinchuriki: 'Gaara (5th Kazekage) & Priest Bunpuku',
    connectionSummary:
      "Originally sealed inside a tea kettle and watched over by priest Bunpuku, Shukaku was later transferred into Gaara by Rasa to safeguard Sunagakure's borders. The bond evolved from violent insomnia into an enduring alliance during the Fourth Shinobi World War.",
    traitsTitleClass: 'text-gold',
    traitsTitleIcon: 'fa-bolt',
    traits: [
      {
        title: 'Magnet Release (Jiton)',
        desc: 'Harnesses innate magnetic chakra infused with ancient cursed seal scripts.',
      },
      {
        title: 'Sand Bullet Barrage',
        desc: 'Pressurizes desert sand into devastating pneumatic artillery strikes.',
      },
      {
        title: 'Desert Layered Imperial Funeral',
        desc: 'Encases colossal targets in miles of pressurized sand pyramids.',
      },
    ],
  },
  {
    id: 'bijuu-matatabi',
    num: '02',
    tailNum: '02 TAILS',
    tailKanji: '二尾 (NIBI)',
    stageClass: 'stage-matatabi',
    auraClass: 'aura-matatabi',
    badgeThemeClass: 'badge-blue-theme',
    domainIcon: 'fa-fire',
    domainTag: 'BLUE FLAME // KUMOGAKURE ALLOCATION',
    frameClass: 'frame-matatabi',
    image: '/assets/image/bijuu_02_matatabi.png',
    imageAlt: 'Matatabi the Two-Tails',
    imgClass: 'img-matatabi',
    stampClass: 'stamp-blue',
    stampKanji: '雷',
    stampLabel: 'CLOUD EMBLEM',
    metrics: [
      {
        label: 'ELEMENTAL AFFINITIES',
        value: 'FIRE (火遁 - BLUE FLAME)',
        valueClass: 'highlight-cyan',
      },
      {
        label: 'COMBAT ARCHETYPE',
        value: 'FLEET AGILITY & SCORCHING INCINERATION',
      },
      {
        label: 'DETERRENCE STATUS',
        value: 'SPEED VANGUARD OF KUMOGAKURE',
        valueClass: 'highlight-cyan',
      },
    ],
    intelBadgeIcon: 'fa-paw',
    intelBadgeText: 'BIJUU DOSSIER // 02',
    name: 'MATATABI',
    nameClass: 'text-cyan',
    kanjiTitle: '二尾・又旅 (THE BLUE FLAME MONSTER CAT)',
    kanjiClass: 'text-cyan',
    synopsis:
      'A colossal feline beast composed entirely of engulfing cobalt-blue spiritual flames trimmed with black markings. Known as the Monster Cat (Bakeneko), Matatabi is renowned for its courteous speech, polite demeanor, and unmatched swiftness across difficult mountainous terrain.',
    connectionBorderClass: 'border-cyan',
    historicalVillage: 'Kumogakure (Hidden Cloud)',
    historicalVillageIcon: 'fa-bolt',
    historicalVillageClass: 'text-cyan',
    primaryJinchuriki: 'Yugito Nii (Kumo Jōnin Master)',
    connectionSummary:
      "Allocated to the Land of Lightning during the First Kage Summit. Through relentless tactical discipline, Yugito Nii achieved voluntary full-body transformation, earning high respect as Kumogakure's pride before facing Hidan and Kakuzu.",
    traitsTitleClass: 'text-cyan',
    traitsTitleIcon: 'fa-fire-burner',
    traits: [
      {
        title: 'Ghostly Blue Fireball',
        desc: 'Fires concentrated blue blaze spheres that explode into blazing pyres.',
      },
      {
        title: 'Flexible Claws & Agility',
        desc: 'Shreds solid stone with flexible fiery claws while moving at blinding speeds.',
      },
      {
        title: 'Polite Demeanor',
        desc: 'Unlike hostile beasts, Matatabi speaks with refined honorifics to fellow spirits.',
      },
    ],
  },
  {
    id: 'bijuu-isobu',
    num: '03',
    tailNum: '03 TAILS',
    tailKanji: '三尾 (SANBI)',
    stageClass: 'stage-isobu',
    auraClass: 'aura-isobu',
    badgeThemeClass: 'badge-mist-theme',
    domainIcon: 'fa-water',
    domainTag: 'OCEAN DEEPS // KIRIGAKURE MILITARY HISTORY',
    frameClass: 'frame-isobu',
    image: '/assets/image/bijuu_03_isobu.png',
    imageAlt: 'Isobu the Three-Tails',
    imgClass: 'img-isobu',
    stampClass: 'stamp-mist',
    stampKanji: '霧',
    stampLabel: 'MIST EMBLEM',
    metrics: [
      {
        label: 'ELEMENTAL AFFINITIES',
        value: 'WATER (水遁) • CORAL (珊瑚) • ILLUSION MIST',
        valueClass: 'highlight-cyan',
      },
      {
        label: 'COMBAT ARCHETYPE',
        value: 'HEAVY ARMORED SHELL & SUBMERGED FORCE',
      },
      {
        label: 'DETERRENCE STATUS',
        value: 'MARITIME GUARDIAN OF THE MIST',
        valueClass: 'highlight-cyan',
      },
    ],
    intelBadgeIcon: 'fa-water',
    intelBadgeText: 'BIJUU DOSSIER // 03',
    name: 'ISOBU',
    nameClass: 'text-mist',
    kanjiTitle: '三尾・磯撫 (THE GIANT ARMORED TURTLE)',
    kanjiClass: 'text-mist',
    synopsis:
      'A massive sea-dwelling turtle enveloped by an impenetrable spiky carapace and crab-like plating. Isobu rules the deep waters, generating tidal surges and hallucinogenic mist capable of confusing entire enemy divisions before crushing them in a rolling shell charge.',
    connectionBorderClass: 'border-mist',
    historicalVillage: 'Kirigakure (Hidden Mist)',
    historicalVillageIcon: 'fa-droplet',
    historicalVillageClass: 'text-mist',
    primaryJinchuriki: 'Yagura Karatachi (4th Mizukage) & Rin Nohara',
    connectionSummary:
      'Forced into Rin Nohara in a covert plot during the Third Shinobi War, Isobu later bonded with Fourth Mizukage Yagura Karatachi, who mastered full mutual control before being manipulated in the shadows by Obito Uchiha.',
    traitsTitleClass: 'text-mist',
    traitsTitleIcon: 'fa-shield',
    traits: [
      {
        title: 'Coral Palm Infliction',
        desc: 'Sprouts dense coral formations on targets to completely freeze their movement.',
      },
      {
        title: 'Shadow Rolling Shell',
        desc: 'Curls into a colossal spiked sphere to crush entire coastlines.',
      },
      {
        title: 'Illusion Mist Deception',
        desc: 'Releases dense fog that traps pursuers in waking nightmare genjutsu.',
      },
    ],
  },
  {
    id: 'bijuu-son-goku',
    num: '04',
    tailNum: '04 TAILS',
    tailKanji: '四尾 (YONBI)',
    stageClass: 'stage-son-goku',
    auraClass: 'aura-son-goku',
    badgeThemeClass: 'badge-lava-theme',
    domainIcon: 'fa-volcano',
    domainTag: 'VOLCANIC MAGMA // IWAGAKURE HERITAGE',
    frameClass: 'frame-son-goku',
    image: '/assets/image/bijuu_04_son_goku.png',
    imageAlt: 'Son Goku the Four-Tails',
    imgClass: 'img-son-goku',
    stampClass: 'stamp-lava',
    stampKanji: '岩',
    stampLabel: 'STONE EMBLEM',
    metrics: [
      {
        label: 'ELEMENTAL AFFINITIES',
        value: 'FIRE (火) + EARTH (土) = LAVA RELEASE (熔遁)',
        valueClass: 'highlight-red',
      },
      {
        label: 'COMBAT ARCHETYPE',
        value: 'MOLTEN CRAGS & TITANIC PHYSICAL BRAWLING',
      },
      {
        label: 'DETERRENCE STATUS',
        value: 'VOLCANIC VANGUARD OF IWAGAKURE',
        valueClass: 'highlight-red',
      },
    ],
    intelBadgeIcon: 'fa-volcano',
    intelBadgeText: 'BIJUU DOSSIER // 04',
    name: 'SON GOKŪ',
    nameClass: 'text-lava',
    kanjiTitle: '四尾・孫悟空 (THE MONKEY KING OF SAGE CAVES)',
    kanjiClass: 'text-lava',
    synopsis:
      'The proud Monkey King (Suitentei) of the Water Screen Cave. Son Gokū resembles a red-furred, green-skinned gorilla wielding the devastating power of Lava Release (Yōton), capable of spitting molten boulders and incinerating entire battlefield sectors.',
    connectionBorderClass: 'border-lava',
    historicalVillage: 'Iwagakure (Hidden Stone)',
    historicalVillageIcon: 'fa-mountain',
    historicalVillageClass: 'text-lava',
    primaryJinchuriki: 'Rōshi (Veteran Hermit Shinobi)',
    connectionSummary:
      "Allocated to Iwagakure during the First Kage Summit. Rōshi spent over forty years wandering as an ascetic hermit attempting to understand the beast's true essence before discovering mutual respect alongside Naruto Uzumaki.",
    traitsTitleClass: 'text-lava',
    traitsTitleIcon: 'fa-mountain',
    traits: [
      {
        title: 'Lava Release Scorching',
        desc: 'Melts subterranean rock into torrents of boiling magma at will.',
      },
      {
        title: 'Monkey King Taijutsu',
        desc: 'Deploys colossal brute strength to grapple even the largest summon monsters.',
      },
      {
        title: 'Great Flower-Fruit Mountain',
        desc: 'Detonates a volcanic eruption directly underneath enemy forces.',
      },
    ],
  },
  {
    id: 'bijuu-kokuo',
    num: '05',
    tailNum: '05 TAILS',
    tailKanji: '五尾 (GOBI)',
    stageClass: 'stage-kokuo',
    auraClass: 'aura-kokuo',
    badgeThemeClass: 'badge-steam-theme',
    domainIcon: 'fa-cloud-arrow-up',
    domainTag: 'STEAM RAMMING // IWAGAKURE MILITARY HEAVYWEIGHT',
    frameClass: 'frame-kokuo',
    image: '/assets/image/bijuu_05_kokuo.png',
    imageAlt: 'Kokuo the Five-Tails',
    imgClass: 'img-kokuo',
    stampClass: 'stamp-steam',
    stampKanji: '蒸',
    stampLabel: 'STEAM EMBLEM',
    metrics: [
      {
        label: 'ELEMENTAL AFFINITIES',
        value: 'WATER (水) + FIRE (火) = BOIL RELEASE (沸遁)',
        valueClass: 'highlight-steam',
      },
      {
        label: 'COMBAT ARCHETYPE',
        value: 'VAPOUR PROPULSION & UNRIVALED HORN CHARGES',
      },
      {
        label: 'DETERRENCE STATUS',
        value: 'HEAVY IMPACT DETERRENT OF STONE',
        valueClass: 'highlight-steam',
      },
    ],
    intelBadgeIcon: 'fa-horse',
    intelBadgeText: 'BIJUU DOSSIER // 05',
    name: 'KOKUŌ',
    nameClass: 'text-steam',
    kanjiTitle: '五尾・穆王 (THE WHITE ILLUSION STEED)',
    kanjiClass: 'text-steam',
    synopsis:
      'A magnificent hybrid beast possessing the body of a white horse and the crested head of a dolphin. Kokuō channels Boil Release (Futton) to heat its chakra to boiling point, generating colossal steam propulsion that drives its horn charges through steel barriers.',
    connectionBorderClass: 'border-steam',
    historicalVillage: 'Iwagakure (Hidden Stone)',
    historicalVillageIcon: 'fa-mountain',
    historicalVillageClass: 'text-steam',
    primaryJinchuriki: 'Han (The Steam Shinobi Titan)',
    connectionSummary:
      'Partnered with Han in Iwagakure, Kokuō utilized steam armor to become a living battering ram during border skirmishes. Following its release after the Fourth War, Kokuō chose a secluded, peaceful forest existence away from human conflict.',
    traitsTitleClass: 'text-steam',
    traitsTitleIcon: 'fa-wind',
    traits: [
      {
        title: 'Boil Release Propelled Charge',
        desc: 'Melts steam pressure to accelerate ramming horns with mountain-shattering force.',
      },
      {
        title: 'Horn Breaker Impact',
        desc: 'Physical impacts capable of sending Eight-Tails skidding hundreds of meters.',
      },
      {
        title: 'Quiet Pride',
        desc: 'Values calm natural balance, communicating softly and avoiding pointless war.',
      },
    ],
  },
  {
    id: 'bijuu-saiken',
    num: '06',
    tailNum: '06 TAILS',
    tailKanji: '六尾 (ROKUBI)',
    stageClass: 'stage-saiken',
    auraClass: 'aura-saiken',
    badgeThemeClass: 'badge-acid-theme',
    domainIcon: 'fa-vial',
    domainTag: 'CORROSIVE ACID // KIRIGAKURE REAGENTS',
    frameClass: 'frame-saiken',
    image: '/assets/image/bijuu_06_saiken.png',
    imageAlt: 'Saiken the Six-Tails',
    imgClass: 'img-saiken',
    stampClass: 'stamp-acid',
    stampKanji: '酸',
    stampLabel: 'ACID EMBLEM',
    metrics: [
      {
        label: 'ELEMENTAL AFFINITIES',
        value: 'WATER (水遁) • CORROSIVE ALKALI MUKUS',
        valueClass: 'highlight-acid',
      },
      {
        label: 'COMBAT ARCHETYPE',
        value: 'CORROSIVE GAS & SLIME ABSORPTION',
      },
      {
        label: 'DETERRENCE STATUS',
        value: 'CORROSIVE FLUID ASSET OF THE MIST',
        valueClass: 'highlight-acid',
      },
    ],
    intelBadgeIcon: 'fa-flask',
    intelBadgeText: 'BIJUU DOSSIER // 06',
    name: 'SAIKEN',
    nameClass: 'text-acid',
    kanjiTitle: '六尾・犀犬 (THE GIANT SLIME SLUG)',
    kanjiClass: 'text-acid',
    synopsis:
      'A colossal, white, six-tailed slug covered in a thick layer of viscous, corrosive secretion. Saiken exudes lethal acidic gas and caustic slime that instantaneously dissolves flesh, steel armor, and ninjutsu barriers on contact.',
    connectionBorderClass: 'border-acid',
    historicalVillage: 'Kirigakure (Hidden Mist)',
    historicalVillageIcon: 'fa-droplet',
    historicalVillageClass: 'text-acid',
    primaryJinchuriki: 'Utakata (Rogue Bubble Shinobi)',
    connectionSummary:
      "Sealed within Utakata in Kirigakure, a tragic misunderstanding with master Harusame caused Utakata to flee into exile. Utakata fused Saiken's corrosive fluids with Soap Bubble Ninjutsu (Shabondama) before being captured by Pain's Six Paths.",
    traitsTitleClass: 'text-acid',
    traitsTitleIcon: 'fa-biohazard',
    traits: [
      {
        title: 'Corrosive Gas Spray',
        desc: 'Expels caustic vapor capable of melting entire fortress gates in seconds.',
      },
      {
        title: 'Viscous Mucus Trapping',
        desc: 'Exudes adhesive fluid to anchor, disarm, and suffocate enemy vanguards.',
      },
      {
        title: 'Soft Elastic Form',
        desc: 'Absorbs tremendous kinetic impacts by deforming its gelatinous mass.',
      },
    ],
  },
  {
    id: 'bijuu-chomei',
    num: '07',
    tailNum: '07 TAILS',
    tailKanji: '七尾 (NANABI / SHICHIBI)',
    stageClass: 'stage-chomei',
    auraClass: 'aura-chomei',
    badgeThemeClass: 'badge-forest-theme',
    domainIcon: 'fa-feather-pointed',
    domainTag: 'AERIAL FORESTS // TAKIGAKURE SOVEREIGNTY',
    frameClass: 'frame-chomei',
    image: '/assets/image/bijuu_07_chomei.png',
    imageAlt: 'Chomei the Seven-Tails',
    imgClass: 'img-chomei',
    stampClass: 'stamp-forest',
    stampKanji: '滝',
    stampLabel: 'WATERFALL EMBLEM',
    metrics: [
      {
        label: 'ELEMENTAL AFFINITIES',
        value: 'WIND (風遁) • BLINDING SCALE PHOSPHOR',
        valueClass: 'highlight-forest',
      },
      {
        label: 'COMBAT ARCHETYPE',
        value: 'HIGH-ALTITUDE FLIGHT & INSECT CHITIN STRIKES',
      },
      {
        label: 'DETERRENCE STATUS',
        value: 'SOLE BIJUU ALLOCATED OUTSIDE 5 NATIONS',
        valueClass: 'highlight-forest',
      },
    ],
    intelBadgeIcon: 'fa-bug',
    intelBadgeText: 'BIJUU DOSSIER // 07',
    name: 'CHŌMEI',
    nameClass: 'text-forest',
    kanjiTitle: '七尾・重明 (THE LUCKY SEVEN KABUTOMUSHI)',
    kanjiClass: 'text-forest',
    synopsis:
      'Resembling a colossal armored rhinoceros beetle with six insect wings and one tail making up its seven appendages. Nicknamed "Lucky Seven Chōmei", it is the only Bijuu capable of sustained supersonic flight, firing luminous blinding scale powders.',
    connectionBorderClass: 'border-forest',
    historicalVillage: 'Takigakure (Hidden Waterfall)',
    historicalVillageIcon: 'fa-water',
    historicalVillageClass: 'text-forest',
    primaryJinchuriki: 'Fū (The Spirited Kunoichi)',
    connectionSummary:
      'The sole Bijuu possessed by a minor hidden village (Takigakure). Fū grew up sheltered by village leader Shibuki and sought to befriend one hundred allies during the joint Chūnin Exams before encountering the Akatsuki.',
    traitsTitleClass: 'text-forest',
    traitsTitleIcon: 'fa-angles-up',
    traits: [
      {
        title: 'Blinding Scale Powder',
        desc: 'Releases radiant scales that blind enemy ocular sensors and Sharingan.',
      },
      {
        title: 'Supersonic Aerial Ramming',
        desc: 'Dives at extreme velocities using razor-hard beetle horns.',
      },
      {
        title: 'Cocoon Regeneration',
        desc: 'Weaves dense chakra threads to form protective healing cocoons.',
      },
    ],
  },
  {
    id: 'bijuu-gyuki',
    num: '08',
    tailNum: '08 TAILS',
    tailKanji: '八尾 (HACHIBI)',
    stageClass: 'stage-gyuki',
    auraClass: 'aura-gyuki',
    badgeThemeClass: 'badge-cloud-theme',
    domainIcon: 'fa-bolt',
    domainTag: 'THUNDER PEAKS // KUMOGAKURE PILLAR',
    frameClass: 'frame-gyuki',
    image: '/assets/image/bijuu_08_gyuki.png',
    imageAlt: 'Gyuki the Eight-Tails',
    imgClass: 'img-gyuki',
    stampClass: 'stamp-cloud',
    stampKanji: '雲',
    stampLabel: 'CLOUD EMBLEM',
    metrics: [
      {
        label: 'ELEMENTAL AFFINITIES',
        value: 'SEALING INK (墨) • LIGHTNING INFUSION',
        valueClass: 'highlight-cyan',
      },
      {
        label: 'COMBAT ARCHETYPE',
        value: 'TITANIC MUSCLE BRAWLING & CONTINENTAL TAIL TWISTERS',
      },
      {
        label: 'DETERRENCE STATUS',
        value: 'SUPREME TACTICAL ANCHOR OF KUMO',
        valueClass: 'highlight-cyan',
      },
    ],
    intelBadgeIcon: 'fa-bolt-lightning',
    intelBadgeText: 'BIJUU DOSSIER // 08',
    name: 'GYŪKI',
    nameClass: 'text-kumo',
    kanjiTitle: '八尾・牛鬼 (THE GIANT OX-CEPHALOPOD)',
    kanjiClass: 'text-kumo',
    synopsis:
      'A colossal cephalopod-ox hybrid (Ushi-oni) possessing four muscular horns and eight massive octopus tentacles for tails. Boasting monumental strength second only to Kurama, Gyūki commands blinding ink seals and colossal 360-degree tail twisters.',
    connectionBorderClass: 'border-cloud',
    historicalVillage: 'Kumogakure (Hidden Cloud)',
    historicalVillageIcon: 'fa-bolt',
    historicalVillageClass: 'text-kumo',
    primaryJinchuriki: 'Killer B (Brother of the 4th Raikage) & Blue B',
    connectionSummary:
      "After multiple tragic host failures in Kumogakure, young Killer B matched Gyūki's spirit with pure mutual brotherhood, becoming the world's most renowned Perfect Jinchūriki and master instructor of Tailed Beast cooperation.",
    traitsTitleClass: 'text-kumo',
    traitsTitleIcon: 'fa-tornado',
    traits: [
      {
        title: 'Tailed Beast Eight Twister',
        desc: 'Spins octopus tails with hurricane force to flatten surrounding forests.',
      },
      {
        title: 'Sealing Ink Matrix',
        desc: 'Expels high-density ink clones that bind and immobilize enemy squads.',
      },
      {
        title: 'Rapid Regenerative Tentacles',
        desc: 'Severed tentacles regrow swiftly and can serve as decoy body doubles.',
      },
    ],
  },
  {
    id: 'bijuu-kurama',
    num: '09',
    tailNum: '09 TAILS',
    tailKanji: '九尾 (KYŪBI)',
    stageClass: 'stage-kurama',
    auraClass: 'aura-kurama',
    badgeThemeClass: 'badge-fire-theme',
    domainIcon: 'fa-fire',
    domainTag: 'SUPREME CHAKRA // KONOHAGAKURE PILLAR',
    frameClass: 'frame-kurama',
    image: '/assets/image/bijuu_09_kurama.png?v=3',
    imageAlt: 'Kurama the Nine-Tails',
    imgClass: 'img-kurama',
    stampClass: 'stamp-fire',
    stampKanji: '木',
    stampLabel: 'LEAF SUPREME',
    metrics: [
      {
        label: 'ELEMENTAL AFFINITIES',
        value: 'FIRE (火) • WIND (風) • PRIMORDIAL LIFE FORCE CHAKRA',
        valueClass: 'highlight-gold',
      },
      {
        label: 'COMBAT ARCHETYPE',
        value: 'CONTINENTAL CALAMITY & PLANETARY DETONATIONS',
      },
      {
        label: 'DETERRENCE STATUS',
        value: 'SUPREME POWER OF THE SHINOBI WORLD',
        valueClass: 'highlight-gold',
      },
    ],
    intelBadgeIcon: 'fa-fire',
    intelBadgeText: 'BIJUU DOSSIER // 09',
    name: 'KURAMA',
    nameClass: '',
    kanjiTitle: '九尾・九喇嘛 (THE NINE-TAILED DEMON FOX)',
    kanjiClass: '',
    synopsis:
      'The strongest of the nine Tailed Beasts, Kurama is a colossal nine-tailed Kitsune whose chakra reserves dwarf the other eight beasts combined. Once viewed as an avatar of hatred, Kurama forged a historic bond with Naruto Uzumaki, becoming the ultimate savior of the shinobi world.',
    connectionBorderClass: 'border-leaf',
    historicalVillage: 'Konohagakure (Hidden Leaf)',
    historicalVillageIcon: 'fa-leaf',
    historicalVillageClass: 'text-gold',
    primaryJinchuriki: 'Naruto Uzumaki, Kushina, Mito, Minato',
    connectionSummary:
      "Originally sealed by Hashirama into Mito Uzumaki, transferred to Kushina, and divided into Yin/Yang halves by Minato Namikaze. Through Naruto's unwavering empathy, Kurama shed centuries of hatred to unlock Kurama Mode and save reality from Kaguya Ōtsutsuki.",
    traitsTitleClass: 'text-gold',
    traitsTitleIcon: 'fa-gear',
    traits: [
      {
        title: 'Negative Emotion Sensing',
        desc: 'Detects malicious intent and hidden chakra across entire continents.',
      },
      {
        title: 'Planetary Tailed Beast Ball',
        desc: 'Obliterates entire mountain ranges with a single super-compressed blast.',
      },
      {
        title: 'Baryon Mode Fusion',
        desc: 'Fuses Naruto and Kurama’s chakra nuclei into raw nuclear energy to drain rival lifespans.',
      },
    ],
  },
];

export function getBijuuById(id) {
  return BIJUU_DATA.find((b) => b.id === id) || null;
}
