"""
Django settings for naruto_core project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env if present
env_file = BASE_DIR / '.env'
if not env_file.exists() and (BASE_DIR.parent / '.env').exists():
    env_file = BASE_DIR.parent / '.env'
if env_file.exists():
    with open(env_file, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#') and '=' in line:
                key, _, val = line.partition('=')
                key = key.strip()
                val = val.strip().strip("'\"")
                if key and key not in os.environ:
                    os.environ[key] = val


def get_bool_env(var_name, default=True):
    """Safely parse boolean environment variables."""
    val = os.getenv(var_name)
    if val is None:
        return default
    return val.strip().lower() in ('true', '1', 'yes', 't', 'y', 'on')


def get_list_env(var_name, default=None):
    """Safely parse comma-separated environment variables into a list."""
    val = os.getenv(var_name)
    if val is None or not val.strip():
        return default if default is not None else []
    return [item.strip() for item in val.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-)ou4n-129&awcuwrylr1dt*o!qw*=w1_idc!1=vp#=%456mct5'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_bool_env('DJANGO_DEBUG', default=True)

# Allowed hosts configuration
ALLOWED_HOSTS = get_list_env(
    'DJANGO_ALLOWED_HOSTS',
    default=[
        '127.0.0.1',
        'localhost',
        'testserver',
        'naruto-production-9f86.up.railway.app',
    ]
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'accounts',
    'favorites',
    'archive',
    'world',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'naruto_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'naruto_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DB_ENGINE = os.getenv('DB_ENGINE', 'sqlite').strip().lower()

if DB_ENGINE in ('postgres', 'postgresql', 'psql'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'naruto_db'),
            'USER': os.getenv('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', ''),
            'HOST': os.getenv('POSTGRES_HOST', '127.0.0.1'),
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    p for p in [BASE_DIR / 'assets', BASE_DIR.parent / 'assets'] if p.exists()
]
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
default_mailer_backend = 'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend'
MAILERS = {
    'default': {
        'BACKEND': os.getenv('DJANGO_MAILER_BACKEND', default_mailer_backend),
    },
}


# CORS Configuration
CORS_ALLOWED_ORIGINS = get_list_env(
    'CORS_ALLOWED_ORIGINS',
    default=[
        'http://127.0.0.1:5173',
        'http://localhost:5173',
        'https://naruto-beta.vercel.app',
        'https://naruto-git-main-sa3dany2.vercel.app',
    ]
)
CORS_ALLOW_CREDENTIALS = True


# CSRF Configuration
CSRF_TRUSTED_ORIGINS = get_list_env(
    'CSRF_TRUSTED_ORIGINS',
    default=[
        'http://127.0.0.1:5173',
        'http://localhost:5173',
        'https://naruto-beta.vercel.app',
        'https://naruto-git-main-sa3dany2.vercel.app',
    ]
)
# Cross-Origin Cookie Configuration
# In local development (localhost), 'Lax' is used.
# In production with separate domains (Vercel frontend -> Railway/Render backend),
# modern browsers mandate SameSite='None' together with Secure=True for cross-origin cookie exchange.
default_samesite = 'Lax' if DEBUG else 'None'
SESSION_COOKIE_SAMESITE = os.getenv('SESSION_COOKIE_SAMESITE', default_samesite)
CSRF_COOKIE_SAMESITE = os.getenv('CSRF_COOKIE_SAMESITE', default_samesite)
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_HTTPONLY = True


# Production HTTPS & Cookie Security Settings
# Conditionally applied when DEBUG is False for production readiness
if not DEBUG:
    SESSION_COOKIE_SECURE = get_bool_env('SESSION_COOKIE_SECURE', default=True)
    CSRF_COOKIE_SECURE = get_bool_env('CSRF_COOKIE_SECURE', default=True)
    SECURE_SSL_REDIRECT = get_bool_env('SECURE_SSL_REDIRECT', default=True)
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = get_bool_env('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=True)
    SECURE_HSTS_PRELOAD = get_bool_env('SECURE_HSTS_PRELOAD', default=True)

    if get_bool_env('SECURE_PROXY_SSL_HEADER', default=True):
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
