# Generated by Django 6.1 on 2026-09-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='item_type',
            field=models.CharField(choices=[('shinobi', 'Shinobi'), ('clan', 'Clan'), ('village', 'Village'), ('bijuu', 'Bijuu')], default='shinobi', max_length=32),
        ),
    ]
