# Generated by Django 6.1 on 2026-09-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shinobi',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('kanji', models.CharField(max_length=32)),
                ('village', models.CharField(db_index=True, max_length=32)),
                ('villageDisplay', models.CharField(max_length=64)),
                ('clan', models.CharField(db_index=True, max_length=32)),
                ('clanDisplay', models.CharField(max_length=64)),
                ('rank', models.CharField(db_index=True, max_length=32)),
                ('rankDisplay', models.CharField(max_length=64)),
                ('status', models.CharField(db_index=True, max_length=32)),
                ('image', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=128)),
                ('natures', models.CharField(max_length=128)),
                ('classification', models.CharField(max_length=128)),
                ('summary', models.TextField()),
                ('techniques', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Shinobi',
                'verbose_name_plural': 'Shinobi',
                'ordering': ['id'],
            },
        ),
    ]
